[Postgres]
user="Saleos"
password="Saleos"
port=5432
host="localhost"

[minio]
host="localhost"
endpoint_port=9000
console_port=9001
accesskey="minioadmin"
security="minioadmin"
bucketname="article"

[Saleos.Admin]
# the host port which you could visited the admin page
port=3232
